---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

notifications:
  email: false

stages:
  - tests
  - versioned tests
  - deploy

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: tests
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:js
        - yarn test

    - stage: versioned tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
