---
language: node_js
node_js:
  - "6"

sudo: true
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

install:
  - yarn install

script:
  - yarn lint:js
  # We need to cleanup, since our deploy depends on the git repo's status
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

notifications:
  email: false

stages:
  - versioned tests
  - deploy

jobs:
  fail_fast: true

  include:
    - stage: versioned tests
    - env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default

    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production

  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
